# Generated by Django 5.2.5 on 2025-05-04 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("namespace", models.CharField(max_length=50)),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_resgistry_system_setting",
                "ordering": ["namespace", "key"],
            },
        ),
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(fields=["namespace"], name="system_resg_namespace_9fd7c0_idx"),
        ),
        migrations.AddIndex(
            model_name="systemsetting",
            index=models.Index(
                fields=["namespace", "key"],
                name="system_resg_namespace_6cf6ee_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemsetting",
            constraint=models.UniqueConstraint(
                fields=("namespace", "key"),
                name="system_resgistry_namespace_key_unique",
            ),
        ),
    ]
